### PR TITLE
Make sure word-wrap is correct in PDF code blocks

### PR DESCRIPTION
**Pull request by bartvde**
Before:

screen shot 2016-03-22 at 11 03 54

After:

screen shot 2016-03-22 at 11 40 48

### CODE REVIEW

**Comment by SamyPesse** [comment]
I think it can be set for all ebook formats (at https://github.com/GitbookIO/theme-default/blob/master/src/less/ebook/base.less)

**Comment by bartvde** [comment]
ah cool will make the change

**Comment by bartvde** [comment]
PR updated

**Comment by SamyPesse** [comment]
Thanks :+1:

**Pull request merged**
